# Generated by Django 2.2.16 on 2021-02-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruction', '0002_instruction_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('loc', models.CharField(max_length=1024)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='instruction.Instruction')),
            ],
        ),
    ]
