# Generated by Django 2.2.16 on 2021-02-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='instructions',
            new_name='instruction',
        ),
    ]
