# Generated by Django 2.2.16 on 2021-01-27 11:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'store'), (1, 'search')], default=0)),
                ('audio_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('sdp_result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
