# Generated by Django 2.2.16 on 2021-01-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructions', to=settings.AUTH_USER_MODEL),
        ),
    ]
