# Generated by Django 2.2.16 on 2021-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0002_instruction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='item_part',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='loc_part',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
