# Generated by Django 2.2.16 on 2021-03-12 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210226_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='create_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 3, 12, 16, 23, 41, 678918)),
            preserve_default=False,
        ),
    ]
