# Generated by Django 2.2.16 on 2021-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
