# Generated by Django 2.2.16 on 2021-03-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20210316_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationmemberinvitation',
            name='location',
        ),
        migrations.DeleteModel(
            name='LocationMember',
        ),
        migrations.DeleteModel(
            name='LocationMemberInvitation',
        ),
    ]
