# Generated by Django 2.2.16 on 2021-03-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0005_auto_20210317_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'owner'), (1, 'member')], default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='location.Location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
