# Generated by Django 2.2.16 on 2021-03-17 07:37

from django.db import migrations


def init_location_profile(apps, schema_editor):
    User = apps.get_model('users', 'AuthUser')
    Location = apps.get_model('location', 'Location')
    UserSetting = apps.get_model('users', 'UserSettings')
    users = User.objects.all()
    for u in users:
        if u.locations.count() == 0:
            loc = Location.objects.create(
                owner=u,
            )
            loc.save()

        if getattr(u, 'profile', None) is None:
            loc = u.locations.first()
            profile = UserSetting.objects.create(
                user=u,
                default_loc=loc
            )
            profile.save()

    return


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_locationmembership'),
        ('users', '0003_usersettings'),
    ]

    operations = [
        migrations.RunPython(init_location_profile)
    ]
