# Generated by Django 2.2.16 on 2021-04-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20210426_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmemberinvitation',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
